//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PoslovnaLogika.WSOgranicenja {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OgranicenjaServisSoap", Namespace="http://softverprojekat.rs/")]
    public partial class OgranicenjaServis : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback OcenaMinOperationCompleted;
        
        private System.Threading.SendOrPostCallback OcenaMaxOperationCompleted;
        
        private System.Threading.SendOrPostCallback PorukaOcenaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZabraniBuduciDatumOperationCompleted;
        
        private System.Threading.SendOrPostCallback PorukaDatumOperationCompleted;
        
        private System.Threading.SendOrPostCallback KomentarObavezanZaLoshuOcenuOperationCompleted;
        
        private System.Threading.SendOrPostCallback PragLoseOceneOperationCompleted;
        
        private System.Threading.SendOrPostCallback PorukaKomentarOperationCompleted;
        
        private System.Threading.SendOrPostCallback DajPravilaOcenjivanjaOperationCompleted;
        
        private System.Threading.SendOrPostCallback MinDuzinaLozinkeOperationCompleted;
        
        private System.Threading.SendOrPostCallback PorukaLozinkaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmailObavezanOperationCompleted;
        
        private System.Threading.SendOrPostCallback DozvoljenDomenOperationCompleted;
        
        private System.Threading.SendOrPostCallback PorukaEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaxDuzinaNazivaOperationCompleted;
        
        private System.Threading.SendOrPostCallback OpisObavezanOperationCompleted;
        
        private System.Threading.SendOrPostCallback PorukaNazivOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OgranicenjaServis() {
            this.Url = global::PoslovnaLogika.Properties.Settings.Default.PoslovnaLogika_WSOgranicenja_OgranicenjaServis;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event OcenaMinCompletedEventHandler OcenaMinCompleted;
        
        /// <remarks/>
        public event OcenaMaxCompletedEventHandler OcenaMaxCompleted;
        
        /// <remarks/>
        public event PorukaOcenaCompletedEventHandler PorukaOcenaCompleted;
        
        /// <remarks/>
        public event ZabraniBuduciDatumCompletedEventHandler ZabraniBuduciDatumCompleted;
        
        /// <remarks/>
        public event PorukaDatumCompletedEventHandler PorukaDatumCompleted;
        
        /// <remarks/>
        public event KomentarObavezanZaLoshuOcenuCompletedEventHandler KomentarObavezanZaLoshuOcenuCompleted;
        
        /// <remarks/>
        public event PragLoseOceneCompletedEventHandler PragLoseOceneCompleted;
        
        /// <remarks/>
        public event PorukaKomentarCompletedEventHandler PorukaKomentarCompleted;
        
        /// <remarks/>
        public event DajPravilaOcenjivanjaCompletedEventHandler DajPravilaOcenjivanjaCompleted;
        
        /// <remarks/>
        public event MinDuzinaLozinkeCompletedEventHandler MinDuzinaLozinkeCompleted;
        
        /// <remarks/>
        public event PorukaLozinkaCompletedEventHandler PorukaLozinkaCompleted;
        
        /// <remarks/>
        public event EmailObavezanCompletedEventHandler EmailObavezanCompleted;
        
        /// <remarks/>
        public event DozvoljenDomenCompletedEventHandler DozvoljenDomenCompleted;
        
        /// <remarks/>
        public event PorukaEmailCompletedEventHandler PorukaEmailCompleted;
        
        /// <remarks/>
        public event MaxDuzinaNazivaCompletedEventHandler MaxDuzinaNazivaCompleted;
        
        /// <remarks/>
        public event OpisObavezanCompletedEventHandler OpisObavezanCompleted;
        
        /// <remarks/>
        public event PorukaNazivCompletedEventHandler PorukaNazivCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/OcenaMin", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int OcenaMin() {
            object[] results = this.Invoke("OcenaMin", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void OcenaMinAsync() {
            this.OcenaMinAsync(null);
        }
        
        /// <remarks/>
        public void OcenaMinAsync(object userState) {
            if ((this.OcenaMinOperationCompleted == null)) {
                this.OcenaMinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOcenaMinOperationCompleted);
            }
            this.InvokeAsync("OcenaMin", new object[0], this.OcenaMinOperationCompleted, userState);
        }
        
        private void OnOcenaMinOperationCompleted(object arg) {
            if ((this.OcenaMinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OcenaMinCompleted(this, new OcenaMinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/OcenaMax", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int OcenaMax() {
            object[] results = this.Invoke("OcenaMax", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void OcenaMaxAsync() {
            this.OcenaMaxAsync(null);
        }
        
        /// <remarks/>
        public void OcenaMaxAsync(object userState) {
            if ((this.OcenaMaxOperationCompleted == null)) {
                this.OcenaMaxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOcenaMaxOperationCompleted);
            }
            this.InvokeAsync("OcenaMax", new object[0], this.OcenaMaxOperationCompleted, userState);
        }
        
        private void OnOcenaMaxOperationCompleted(object arg) {
            if ((this.OcenaMaxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OcenaMaxCompleted(this, new OcenaMaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/PorukaOcena", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PorukaOcena() {
            object[] results = this.Invoke("PorukaOcena", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PorukaOcenaAsync() {
            this.PorukaOcenaAsync(null);
        }
        
        /// <remarks/>
        public void PorukaOcenaAsync(object userState) {
            if ((this.PorukaOcenaOperationCompleted == null)) {
                this.PorukaOcenaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPorukaOcenaOperationCompleted);
            }
            this.InvokeAsync("PorukaOcena", new object[0], this.PorukaOcenaOperationCompleted, userState);
        }
        
        private void OnPorukaOcenaOperationCompleted(object arg) {
            if ((this.PorukaOcenaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PorukaOcenaCompleted(this, new PorukaOcenaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/ZabraniBuduciDatum", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ZabraniBuduciDatum() {
            object[] results = this.Invoke("ZabraniBuduciDatum", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ZabraniBuduciDatumAsync() {
            this.ZabraniBuduciDatumAsync(null);
        }
        
        /// <remarks/>
        public void ZabraniBuduciDatumAsync(object userState) {
            if ((this.ZabraniBuduciDatumOperationCompleted == null)) {
                this.ZabraniBuduciDatumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZabraniBuduciDatumOperationCompleted);
            }
            this.InvokeAsync("ZabraniBuduciDatum", new object[0], this.ZabraniBuduciDatumOperationCompleted, userState);
        }
        
        private void OnZabraniBuduciDatumOperationCompleted(object arg) {
            if ((this.ZabraniBuduciDatumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZabraniBuduciDatumCompleted(this, new ZabraniBuduciDatumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/PorukaDatum", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PorukaDatum() {
            object[] results = this.Invoke("PorukaDatum", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PorukaDatumAsync() {
            this.PorukaDatumAsync(null);
        }
        
        /// <remarks/>
        public void PorukaDatumAsync(object userState) {
            if ((this.PorukaDatumOperationCompleted == null)) {
                this.PorukaDatumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPorukaDatumOperationCompleted);
            }
            this.InvokeAsync("PorukaDatum", new object[0], this.PorukaDatumOperationCompleted, userState);
        }
        
        private void OnPorukaDatumOperationCompleted(object arg) {
            if ((this.PorukaDatumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PorukaDatumCompleted(this, new PorukaDatumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/KomentarObavezanZaLoshuOcenu", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KomentarObavezanZaLoshuOcenu() {
            object[] results = this.Invoke("KomentarObavezanZaLoshuOcenu", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KomentarObavezanZaLoshuOcenuAsync() {
            this.KomentarObavezanZaLoshuOcenuAsync(null);
        }
        
        /// <remarks/>
        public void KomentarObavezanZaLoshuOcenuAsync(object userState) {
            if ((this.KomentarObavezanZaLoshuOcenuOperationCompleted == null)) {
                this.KomentarObavezanZaLoshuOcenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKomentarObavezanZaLoshuOcenuOperationCompleted);
            }
            this.InvokeAsync("KomentarObavezanZaLoshuOcenu", new object[0], this.KomentarObavezanZaLoshuOcenuOperationCompleted, userState);
        }
        
        private void OnKomentarObavezanZaLoshuOcenuOperationCompleted(object arg) {
            if ((this.KomentarObavezanZaLoshuOcenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KomentarObavezanZaLoshuOcenuCompleted(this, new KomentarObavezanZaLoshuOcenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/PragLoseOcene", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int PragLoseOcene() {
            object[] results = this.Invoke("PragLoseOcene", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void PragLoseOceneAsync() {
            this.PragLoseOceneAsync(null);
        }
        
        /// <remarks/>
        public void PragLoseOceneAsync(object userState) {
            if ((this.PragLoseOceneOperationCompleted == null)) {
                this.PragLoseOceneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPragLoseOceneOperationCompleted);
            }
            this.InvokeAsync("PragLoseOcene", new object[0], this.PragLoseOceneOperationCompleted, userState);
        }
        
        private void OnPragLoseOceneOperationCompleted(object arg) {
            if ((this.PragLoseOceneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PragLoseOceneCompleted(this, new PragLoseOceneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/PorukaKomentar", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PorukaKomentar() {
            object[] results = this.Invoke("PorukaKomentar", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PorukaKomentarAsync() {
            this.PorukaKomentarAsync(null);
        }
        
        /// <remarks/>
        public void PorukaKomentarAsync(object userState) {
            if ((this.PorukaKomentarOperationCompleted == null)) {
                this.PorukaKomentarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPorukaKomentarOperationCompleted);
            }
            this.InvokeAsync("PorukaKomentar", new object[0], this.PorukaKomentarOperationCompleted, userState);
        }
        
        private void OnPorukaKomentarOperationCompleted(object arg) {
            if ((this.PorukaKomentarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PorukaKomentarCompleted(this, new PorukaKomentarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/DajPravilaOcenjivanja", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PraviloOcenjivanjaDto[] DajPravilaOcenjivanja() {
            object[] results = this.Invoke("DajPravilaOcenjivanja", new object[0]);
            return ((PraviloOcenjivanjaDto[])(results[0]));
        }
        
        /// <remarks/>
        public void DajPravilaOcenjivanjaAsync() {
            this.DajPravilaOcenjivanjaAsync(null);
        }
        
        /// <remarks/>
        public void DajPravilaOcenjivanjaAsync(object userState) {
            if ((this.DajPravilaOcenjivanjaOperationCompleted == null)) {
                this.DajPravilaOcenjivanjaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDajPravilaOcenjivanjaOperationCompleted);
            }
            this.InvokeAsync("DajPravilaOcenjivanja", new object[0], this.DajPravilaOcenjivanjaOperationCompleted, userState);
        }
        
        private void OnDajPravilaOcenjivanjaOperationCompleted(object arg) {
            if ((this.DajPravilaOcenjivanjaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DajPravilaOcenjivanjaCompleted(this, new DajPravilaOcenjivanjaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/MinDuzinaLozinke", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int MinDuzinaLozinke() {
            object[] results = this.Invoke("MinDuzinaLozinke", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void MinDuzinaLozinkeAsync() {
            this.MinDuzinaLozinkeAsync(null);
        }
        
        /// <remarks/>
        public void MinDuzinaLozinkeAsync(object userState) {
            if ((this.MinDuzinaLozinkeOperationCompleted == null)) {
                this.MinDuzinaLozinkeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMinDuzinaLozinkeOperationCompleted);
            }
            this.InvokeAsync("MinDuzinaLozinke", new object[0], this.MinDuzinaLozinkeOperationCompleted, userState);
        }
        
        private void OnMinDuzinaLozinkeOperationCompleted(object arg) {
            if ((this.MinDuzinaLozinkeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MinDuzinaLozinkeCompleted(this, new MinDuzinaLozinkeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/PorukaLozinka", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PorukaLozinka() {
            object[] results = this.Invoke("PorukaLozinka", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PorukaLozinkaAsync() {
            this.PorukaLozinkaAsync(null);
        }
        
        /// <remarks/>
        public void PorukaLozinkaAsync(object userState) {
            if ((this.PorukaLozinkaOperationCompleted == null)) {
                this.PorukaLozinkaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPorukaLozinkaOperationCompleted);
            }
            this.InvokeAsync("PorukaLozinka", new object[0], this.PorukaLozinkaOperationCompleted, userState);
        }
        
        private void OnPorukaLozinkaOperationCompleted(object arg) {
            if ((this.PorukaLozinkaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PorukaLozinkaCompleted(this, new PorukaLozinkaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/EmailObavezan", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EmailObavezan() {
            object[] results = this.Invoke("EmailObavezan", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EmailObavezanAsync() {
            this.EmailObavezanAsync(null);
        }
        
        /// <remarks/>
        public void EmailObavezanAsync(object userState) {
            if ((this.EmailObavezanOperationCompleted == null)) {
                this.EmailObavezanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmailObavezanOperationCompleted);
            }
            this.InvokeAsync("EmailObavezan", new object[0], this.EmailObavezanOperationCompleted, userState);
        }
        
        private void OnEmailObavezanOperationCompleted(object arg) {
            if ((this.EmailObavezanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmailObavezanCompleted(this, new EmailObavezanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/DozvoljenDomen", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DozvoljenDomen() {
            object[] results = this.Invoke("DozvoljenDomen", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DozvoljenDomenAsync() {
            this.DozvoljenDomenAsync(null);
        }
        
        /// <remarks/>
        public void DozvoljenDomenAsync(object userState) {
            if ((this.DozvoljenDomenOperationCompleted == null)) {
                this.DozvoljenDomenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDozvoljenDomenOperationCompleted);
            }
            this.InvokeAsync("DozvoljenDomen", new object[0], this.DozvoljenDomenOperationCompleted, userState);
        }
        
        private void OnDozvoljenDomenOperationCompleted(object arg) {
            if ((this.DozvoljenDomenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DozvoljenDomenCompleted(this, new DozvoljenDomenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/PorukaEmail", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PorukaEmail() {
            object[] results = this.Invoke("PorukaEmail", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PorukaEmailAsync() {
            this.PorukaEmailAsync(null);
        }
        
        /// <remarks/>
        public void PorukaEmailAsync(object userState) {
            if ((this.PorukaEmailOperationCompleted == null)) {
                this.PorukaEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPorukaEmailOperationCompleted);
            }
            this.InvokeAsync("PorukaEmail", new object[0], this.PorukaEmailOperationCompleted, userState);
        }
        
        private void OnPorukaEmailOperationCompleted(object arg) {
            if ((this.PorukaEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PorukaEmailCompleted(this, new PorukaEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/MaxDuzinaNaziva", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int MaxDuzinaNaziva() {
            object[] results = this.Invoke("MaxDuzinaNaziva", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void MaxDuzinaNazivaAsync() {
            this.MaxDuzinaNazivaAsync(null);
        }
        
        /// <remarks/>
        public void MaxDuzinaNazivaAsync(object userState) {
            if ((this.MaxDuzinaNazivaOperationCompleted == null)) {
                this.MaxDuzinaNazivaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaxDuzinaNazivaOperationCompleted);
            }
            this.InvokeAsync("MaxDuzinaNaziva", new object[0], this.MaxDuzinaNazivaOperationCompleted, userState);
        }
        
        private void OnMaxDuzinaNazivaOperationCompleted(object arg) {
            if ((this.MaxDuzinaNazivaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaxDuzinaNazivaCompleted(this, new MaxDuzinaNazivaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/OpisObavezan", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool OpisObavezan() {
            object[] results = this.Invoke("OpisObavezan", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void OpisObavezanAsync() {
            this.OpisObavezanAsync(null);
        }
        
        /// <remarks/>
        public void OpisObavezanAsync(object userState) {
            if ((this.OpisObavezanOperationCompleted == null)) {
                this.OpisObavezanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOpisObavezanOperationCompleted);
            }
            this.InvokeAsync("OpisObavezan", new object[0], this.OpisObavezanOperationCompleted, userState);
        }
        
        private void OnOpisObavezanOperationCompleted(object arg) {
            if ((this.OpisObavezanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OpisObavezanCompleted(this, new OpisObavezanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://softverprojekat.rs/PorukaNaziv", RequestNamespace="http://softverprojekat.rs/", ResponseNamespace="http://softverprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PorukaNaziv() {
            object[] results = this.Invoke("PorukaNaziv", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PorukaNazivAsync() {
            this.PorukaNazivAsync(null);
        }
        
        /// <remarks/>
        public void PorukaNazivAsync(object userState) {
            if ((this.PorukaNazivOperationCompleted == null)) {
                this.PorukaNazivOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPorukaNazivOperationCompleted);
            }
            this.InvokeAsync("PorukaNaziv", new object[0], this.PorukaNazivOperationCompleted, userState);
        }
        
        private void OnPorukaNazivOperationCompleted(object arg) {
            if ((this.PorukaNazivCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PorukaNazivCompleted(this, new PorukaNazivCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softverprojekat.rs/")]
    public partial class PraviloOcenjivanjaDto {
        
        private int ocenaField;
        
        private string akcijaField;
        
        private string opisField;
        
        /// <remarks/>
        public int Ocena {
            get {
                return this.ocenaField;
            }
            set {
                this.ocenaField = value;
            }
        }
        
        /// <remarks/>
        public string Akcija {
            get {
                return this.akcijaField;
            }
            set {
                this.akcijaField = value;
            }
        }
        
        /// <remarks/>
        public string Opis {
            get {
                return this.opisField;
            }
            set {
                this.opisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void OcenaMinCompletedEventHandler(object sender, OcenaMinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OcenaMinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OcenaMinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void OcenaMaxCompletedEventHandler(object sender, OcenaMaxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OcenaMaxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OcenaMaxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PorukaOcenaCompletedEventHandler(object sender, PorukaOcenaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PorukaOcenaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PorukaOcenaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ZabraniBuduciDatumCompletedEventHandler(object sender, ZabraniBuduciDatumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZabraniBuduciDatumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZabraniBuduciDatumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PorukaDatumCompletedEventHandler(object sender, PorukaDatumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PorukaDatumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PorukaDatumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void KomentarObavezanZaLoshuOcenuCompletedEventHandler(object sender, KomentarObavezanZaLoshuOcenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KomentarObavezanZaLoshuOcenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KomentarObavezanZaLoshuOcenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PragLoseOceneCompletedEventHandler(object sender, PragLoseOceneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PragLoseOceneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PragLoseOceneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PorukaKomentarCompletedEventHandler(object sender, PorukaKomentarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PorukaKomentarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PorukaKomentarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DajPravilaOcenjivanjaCompletedEventHandler(object sender, DajPravilaOcenjivanjaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DajPravilaOcenjivanjaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DajPravilaOcenjivanjaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PraviloOcenjivanjaDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PraviloOcenjivanjaDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void MinDuzinaLozinkeCompletedEventHandler(object sender, MinDuzinaLozinkeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MinDuzinaLozinkeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MinDuzinaLozinkeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PorukaLozinkaCompletedEventHandler(object sender, PorukaLozinkaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PorukaLozinkaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PorukaLozinkaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void EmailObavezanCompletedEventHandler(object sender, EmailObavezanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmailObavezanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmailObavezanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DozvoljenDomenCompletedEventHandler(object sender, DozvoljenDomenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DozvoljenDomenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DozvoljenDomenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PorukaEmailCompletedEventHandler(object sender, PorukaEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PorukaEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PorukaEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void MaxDuzinaNazivaCompletedEventHandler(object sender, MaxDuzinaNazivaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaxDuzinaNazivaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaxDuzinaNazivaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void OpisObavezanCompletedEventHandler(object sender, OpisObavezanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OpisObavezanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OpisObavezanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PorukaNazivCompletedEventHandler(object sender, PorukaNazivCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PorukaNazivCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PorukaNazivCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591