//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace KorisnickiInterfejs
{


     public partial class EvidencijaEdit
     {

          /// <summary>
          /// gvEvidencije control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.GridView gvEvidencije;

          /// <summary>
          /// pnlUredi control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Panel pnlUredi;

          /// <summary>
          /// pnlPoruka control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Panel pnlPoruka;

          /// <summary>
          /// lblPoruka control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblPoruka;

          /// <summary>
          /// hfEvidencijaID control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.HiddenField hfEvidencijaID;

          /// <summary>
          /// ddlKorisnik control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.DropDownList ddlKorisnik;

          /// <summary>
          /// ddlKriterijum control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.DropDownList ddlKriterijum;

          /// <summary>
          /// txtOcena control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtOcena;

          /// <summary>
          /// txtKomentar control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtKomentar;

          /// <summary>
          /// btnObrisi control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Button btnObrisi;

          /// <summary>
          /// btnSacuvaj control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Button btnSacuvaj;
     }
}
