//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PrezentacionaLogika.WebOgranicenjaServis {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OgranicenjaServisSoap", Namespace="http://tvojprojekat.rs/")]
    public partial class OgranicenjaServis : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback OpisObavezanOperationCompleted;
        
        private System.Threading.SendOrPostCallback PorukaOpisOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZabraniBuduciDatumOperationCompleted;
        
        private System.Threading.SendOrPostCallback PorukaDatumOperationCompleted;
        
        private System.Threading.SendOrPostCallback DajSezonskaPravilaOperationCompleted;
        
        private System.Threading.SendOrPostCallback MinimalnaPovrsinaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DozvoliPreklapanjeOperationCompleted;
        
        private System.Threading.SendOrPostCallback PorukaPreklapanjeOperationCompleted;
        
        private System.Threading.SendOrPostCallback FullAmountRequiresAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObavezneAktivnostiOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelimicnoOdobrenjeDozvoljenoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelimicnoOdobrenjeNacinOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcenatPoAktivnostiOperationCompleted;
        
        private System.Threading.SendOrPostCallback PorukaAkoNijePunoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OgranicenjaServis() {
            this.Url = global::PrezentacionaLogika.Properties.Settings.Default.PrezentacionaLogika_OgranicenjaServis_OgranicenjaServis;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event OpisObavezanCompletedEventHandler OpisObavezanCompleted;
        
        /// <remarks/>
        public event PorukaOpisCompletedEventHandler PorukaOpisCompleted;
        
        /// <remarks/>
        public event ZabraniBuduciDatumCompletedEventHandler ZabraniBuduciDatumCompleted;
        
        /// <remarks/>
        public event PorukaDatumCompletedEventHandler PorukaDatumCompleted;
        
        /// <remarks/>
        public event DajSezonskaPravilaCompletedEventHandler DajSezonskaPravilaCompleted;
        
        /// <remarks/>
        public event MinimalnaPovrsinaCompletedEventHandler MinimalnaPovrsinaCompleted;
        
        /// <remarks/>
        public event DozvoliPreklapanjeCompletedEventHandler DozvoliPreklapanjeCompleted;
        
        /// <remarks/>
        public event PorukaPreklapanjeCompletedEventHandler PorukaPreklapanjeCompleted;
        
        /// <remarks/>
        public event FullAmountRequiresAllCompletedEventHandler FullAmountRequiresAllCompleted;
        
        /// <remarks/>
        public event ObavezneAktivnostiCompletedEventHandler ObavezneAktivnostiCompleted;
        
        /// <remarks/>
        public event DelimicnoOdobrenjeDozvoljenoCompletedEventHandler DelimicnoOdobrenjeDozvoljenoCompleted;
        
        /// <remarks/>
        public event DelimicnoOdobrenjeNacinCompletedEventHandler DelimicnoOdobrenjeNacinCompleted;
        
        /// <remarks/>
        public event ProcenatPoAktivnostiCompletedEventHandler ProcenatPoAktivnostiCompleted;
        
        /// <remarks/>
        public event PorukaAkoNijePunoCompletedEventHandler PorukaAkoNijePunoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tvojprojekat.rs/OpisObavezan", RequestNamespace="http://tvojprojekat.rs/", ResponseNamespace="http://tvojprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool OpisObavezan() {
            object[] results = this.Invoke("OpisObavezan", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void OpisObavezanAsync() {
            this.OpisObavezanAsync(null);
        }
        
        /// <remarks/>
        public void OpisObavezanAsync(object userState) {
            if ((this.OpisObavezanOperationCompleted == null)) {
                this.OpisObavezanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOpisObavezanOperationCompleted);
            }
            this.InvokeAsync("OpisObavezan", new object[0], this.OpisObavezanOperationCompleted, userState);
        }
        
        private void OnOpisObavezanOperationCompleted(object arg) {
            if ((this.OpisObavezanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OpisObavezanCompleted(this, new OpisObavezanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tvojprojekat.rs/PorukaOpis", RequestNamespace="http://tvojprojekat.rs/", ResponseNamespace="http://tvojprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PorukaOpis() {
            object[] results = this.Invoke("PorukaOpis", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PorukaOpisAsync() {
            this.PorukaOpisAsync(null);
        }
        
        /// <remarks/>
        public void PorukaOpisAsync(object userState) {
            if ((this.PorukaOpisOperationCompleted == null)) {
                this.PorukaOpisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPorukaOpisOperationCompleted);
            }
            this.InvokeAsync("PorukaOpis", new object[0], this.PorukaOpisOperationCompleted, userState);
        }
        
        private void OnPorukaOpisOperationCompleted(object arg) {
            if ((this.PorukaOpisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PorukaOpisCompleted(this, new PorukaOpisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tvojprojekat.rs/ZabraniBuduciDatum", RequestNamespace="http://tvojprojekat.rs/", ResponseNamespace="http://tvojprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ZabraniBuduciDatum() {
            object[] results = this.Invoke("ZabraniBuduciDatum", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ZabraniBuduciDatumAsync() {
            this.ZabraniBuduciDatumAsync(null);
        }
        
        /// <remarks/>
        public void ZabraniBuduciDatumAsync(object userState) {
            if ((this.ZabraniBuduciDatumOperationCompleted == null)) {
                this.ZabraniBuduciDatumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZabraniBuduciDatumOperationCompleted);
            }
            this.InvokeAsync("ZabraniBuduciDatum", new object[0], this.ZabraniBuduciDatumOperationCompleted, userState);
        }
        
        private void OnZabraniBuduciDatumOperationCompleted(object arg) {
            if ((this.ZabraniBuduciDatumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZabraniBuduciDatumCompleted(this, new ZabraniBuduciDatumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tvojprojekat.rs/PorukaDatum", RequestNamespace="http://tvojprojekat.rs/", ResponseNamespace="http://tvojprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PorukaDatum() {
            object[] results = this.Invoke("PorukaDatum", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PorukaDatumAsync() {
            this.PorukaDatumAsync(null);
        }
        
        /// <remarks/>
        public void PorukaDatumAsync(object userState) {
            if ((this.PorukaDatumOperationCompleted == null)) {
                this.PorukaDatumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPorukaDatumOperationCompleted);
            }
            this.InvokeAsync("PorukaDatum", new object[0], this.PorukaDatumOperationCompleted, userState);
        }
        
        private void OnPorukaDatumOperationCompleted(object arg) {
            if ((this.PorukaDatumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PorukaDatumCompleted(this, new PorukaDatumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tvojprojekat.rs/DajSezonskaPravila", RequestNamespace="http://tvojprojekat.rs/", ResponseNamespace="http://tvojprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SezonaDto[] DajSezonskaPravila() {
            object[] results = this.Invoke("DajSezonskaPravila", new object[0]);
            return ((SezonaDto[])(results[0]));
        }
        
        /// <remarks/>
        public void DajSezonskaPravilaAsync() {
            this.DajSezonskaPravilaAsync(null);
        }
        
        /// <remarks/>
        public void DajSezonskaPravilaAsync(object userState) {
            if ((this.DajSezonskaPravilaOperationCompleted == null)) {
                this.DajSezonskaPravilaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDajSezonskaPravilaOperationCompleted);
            }
            this.InvokeAsync("DajSezonskaPravila", new object[0], this.DajSezonskaPravilaOperationCompleted, userState);
        }
        
        private void OnDajSezonskaPravilaOperationCompleted(object arg) {
            if ((this.DajSezonskaPravilaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DajSezonskaPravilaCompleted(this, new DajSezonskaPravilaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tvojprojekat.rs/MinimalnaPovrsina", RequestNamespace="http://tvojprojekat.rs/", ResponseNamespace="http://tvojprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal MinimalnaPovrsina() {
            object[] results = this.Invoke("MinimalnaPovrsina", new object[0]);
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void MinimalnaPovrsinaAsync() {
            this.MinimalnaPovrsinaAsync(null);
        }
        
        /// <remarks/>
        public void MinimalnaPovrsinaAsync(object userState) {
            if ((this.MinimalnaPovrsinaOperationCompleted == null)) {
                this.MinimalnaPovrsinaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMinimalnaPovrsinaOperationCompleted);
            }
            this.InvokeAsync("MinimalnaPovrsina", new object[0], this.MinimalnaPovrsinaOperationCompleted, userState);
        }
        
        private void OnMinimalnaPovrsinaOperationCompleted(object arg) {
            if ((this.MinimalnaPovrsinaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MinimalnaPovrsinaCompleted(this, new MinimalnaPovrsinaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tvojprojekat.rs/DozvoliPreklapanje", RequestNamespace="http://tvojprojekat.rs/", ResponseNamespace="http://tvojprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DozvoliPreklapanje() {
            object[] results = this.Invoke("DozvoliPreklapanje", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DozvoliPreklapanjeAsync() {
            this.DozvoliPreklapanjeAsync(null);
        }
        
        /// <remarks/>
        public void DozvoliPreklapanjeAsync(object userState) {
            if ((this.DozvoliPreklapanjeOperationCompleted == null)) {
                this.DozvoliPreklapanjeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDozvoliPreklapanjeOperationCompleted);
            }
            this.InvokeAsync("DozvoliPreklapanje", new object[0], this.DozvoliPreklapanjeOperationCompleted, userState);
        }
        
        private void OnDozvoliPreklapanjeOperationCompleted(object arg) {
            if ((this.DozvoliPreklapanjeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DozvoliPreklapanjeCompleted(this, new DozvoliPreklapanjeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tvojprojekat.rs/PorukaPreklapanje", RequestNamespace="http://tvojprojekat.rs/", ResponseNamespace="http://tvojprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PorukaPreklapanje() {
            object[] results = this.Invoke("PorukaPreklapanje", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PorukaPreklapanjeAsync() {
            this.PorukaPreklapanjeAsync(null);
        }
        
        /// <remarks/>
        public void PorukaPreklapanjeAsync(object userState) {
            if ((this.PorukaPreklapanjeOperationCompleted == null)) {
                this.PorukaPreklapanjeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPorukaPreklapanjeOperationCompleted);
            }
            this.InvokeAsync("PorukaPreklapanje", new object[0], this.PorukaPreklapanjeOperationCompleted, userState);
        }
        
        private void OnPorukaPreklapanjeOperationCompleted(object arg) {
            if ((this.PorukaPreklapanjeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PorukaPreklapanjeCompleted(this, new PorukaPreklapanjeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tvojprojekat.rs/FullAmountRequiresAll", RequestNamespace="http://tvojprojekat.rs/", ResponseNamespace="http://tvojprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool FullAmountRequiresAll() {
            object[] results = this.Invoke("FullAmountRequiresAll", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void FullAmountRequiresAllAsync() {
            this.FullAmountRequiresAllAsync(null);
        }
        
        /// <remarks/>
        public void FullAmountRequiresAllAsync(object userState) {
            if ((this.FullAmountRequiresAllOperationCompleted == null)) {
                this.FullAmountRequiresAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFullAmountRequiresAllOperationCompleted);
            }
            this.InvokeAsync("FullAmountRequiresAll", new object[0], this.FullAmountRequiresAllOperationCompleted, userState);
        }
        
        private void OnFullAmountRequiresAllOperationCompleted(object arg) {
            if ((this.FullAmountRequiresAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FullAmountRequiresAllCompleted(this, new FullAmountRequiresAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tvojprojekat.rs/ObavezneAktivnosti", RequestNamespace="http://tvojprojekat.rs/", ResponseNamespace="http://tvojprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ObaveznaAktivnostDto[] ObavezneAktivnosti() {
            object[] results = this.Invoke("ObavezneAktivnosti", new object[0]);
            return ((ObaveznaAktivnostDto[])(results[0]));
        }
        
        /// <remarks/>
        public void ObavezneAktivnostiAsync() {
            this.ObavezneAktivnostiAsync(null);
        }
        
        /// <remarks/>
        public void ObavezneAktivnostiAsync(object userState) {
            if ((this.ObavezneAktivnostiOperationCompleted == null)) {
                this.ObavezneAktivnostiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObavezneAktivnostiOperationCompleted);
            }
            this.InvokeAsync("ObavezneAktivnosti", new object[0], this.ObavezneAktivnostiOperationCompleted, userState);
        }
        
        private void OnObavezneAktivnostiOperationCompleted(object arg) {
            if ((this.ObavezneAktivnostiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObavezneAktivnostiCompleted(this, new ObavezneAktivnostiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tvojprojekat.rs/DelimicnoOdobrenjeDozvoljeno", RequestNamespace="http://tvojprojekat.rs/", ResponseNamespace="http://tvojprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DelimicnoOdobrenjeDozvoljeno() {
            object[] results = this.Invoke("DelimicnoOdobrenjeDozvoljeno", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DelimicnoOdobrenjeDozvoljenoAsync() {
            this.DelimicnoOdobrenjeDozvoljenoAsync(null);
        }
        
        /// <remarks/>
        public void DelimicnoOdobrenjeDozvoljenoAsync(object userState) {
            if ((this.DelimicnoOdobrenjeDozvoljenoOperationCompleted == null)) {
                this.DelimicnoOdobrenjeDozvoljenoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelimicnoOdobrenjeDozvoljenoOperationCompleted);
            }
            this.InvokeAsync("DelimicnoOdobrenjeDozvoljeno", new object[0], this.DelimicnoOdobrenjeDozvoljenoOperationCompleted, userState);
        }
        
        private void OnDelimicnoOdobrenjeDozvoljenoOperationCompleted(object arg) {
            if ((this.DelimicnoOdobrenjeDozvoljenoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelimicnoOdobrenjeDozvoljenoCompleted(this, new DelimicnoOdobrenjeDozvoljenoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tvojprojekat.rs/DelimicnoOdobrenjeNacin", RequestNamespace="http://tvojprojekat.rs/", ResponseNamespace="http://tvojprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DelimicnoOdobrenjeNacin() {
            object[] results = this.Invoke("DelimicnoOdobrenjeNacin", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DelimicnoOdobrenjeNacinAsync() {
            this.DelimicnoOdobrenjeNacinAsync(null);
        }
        
        /// <remarks/>
        public void DelimicnoOdobrenjeNacinAsync(object userState) {
            if ((this.DelimicnoOdobrenjeNacinOperationCompleted == null)) {
                this.DelimicnoOdobrenjeNacinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelimicnoOdobrenjeNacinOperationCompleted);
            }
            this.InvokeAsync("DelimicnoOdobrenjeNacin", new object[0], this.DelimicnoOdobrenjeNacinOperationCompleted, userState);
        }
        
        private void OnDelimicnoOdobrenjeNacinOperationCompleted(object arg) {
            if ((this.DelimicnoOdobrenjeNacinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelimicnoOdobrenjeNacinCompleted(this, new DelimicnoOdobrenjeNacinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tvojprojekat.rs/ProcenatPoAktivnosti", RequestNamespace="http://tvojprojekat.rs/", ResponseNamespace="http://tvojprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal ProcenatPoAktivnosti() {
            object[] results = this.Invoke("ProcenatPoAktivnosti", new object[0]);
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void ProcenatPoAktivnostiAsync() {
            this.ProcenatPoAktivnostiAsync(null);
        }
        
        /// <remarks/>
        public void ProcenatPoAktivnostiAsync(object userState) {
            if ((this.ProcenatPoAktivnostiOperationCompleted == null)) {
                this.ProcenatPoAktivnostiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcenatPoAktivnostiOperationCompleted);
            }
            this.InvokeAsync("ProcenatPoAktivnosti", new object[0], this.ProcenatPoAktivnostiOperationCompleted, userState);
        }
        
        private void OnProcenatPoAktivnostiOperationCompleted(object arg) {
            if ((this.ProcenatPoAktivnostiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcenatPoAktivnostiCompleted(this, new ProcenatPoAktivnostiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tvojprojekat.rs/PorukaAkoNijePuno", RequestNamespace="http://tvojprojekat.rs/", ResponseNamespace="http://tvojprojekat.rs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PorukaAkoNijePuno() {
            object[] results = this.Invoke("PorukaAkoNijePuno", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PorukaAkoNijePunoAsync() {
            this.PorukaAkoNijePunoAsync(null);
        }
        
        /// <remarks/>
        public void PorukaAkoNijePunoAsync(object userState) {
            if ((this.PorukaAkoNijePunoOperationCompleted == null)) {
                this.PorukaAkoNijePunoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPorukaAkoNijePunoOperationCompleted);
            }
            this.InvokeAsync("PorukaAkoNijePuno", new object[0], this.PorukaAkoNijePunoOperationCompleted, userState);
        }
        
        private void OnPorukaAkoNijePunoOperationCompleted(object arg) {
            if ((this.PorukaAkoNijePunoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PorukaAkoNijePunoCompleted(this, new PorukaAkoNijePunoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tvojprojekat.rs/")]
    public partial class SezonaDto {
        
        private int tipIdField;
        
        private string odField;
        
        private string doField;
        
        private string opisField;
        
        /// <remarks/>
        public int TipId {
            get {
                return this.tipIdField;
            }
            set {
                this.tipIdField = value;
            }
        }
        
        /// <remarks/>
        public string Od {
            get {
                return this.odField;
            }
            set {
                this.odField = value;
            }
        }
        
        /// <remarks/>
        public string Do {
            get {
                return this.doField;
            }
            set {
                this.doField = value;
            }
        }
        
        /// <remarks/>
        public string Opis {
            get {
                return this.opisField;
            }
            set {
                this.opisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tvojprojekat.rs/")]
    public partial class ObaveznaAktivnostDto {
        
        private int tipIdField;
        
        private string nazivField;
        
        /// <remarks/>
        public int TipId {
            get {
                return this.tipIdField;
            }
            set {
                this.tipIdField = value;
            }
        }
        
        /// <remarks/>
        public string Naziv {
            get {
                return this.nazivField;
            }
            set {
                this.nazivField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void OpisObavezanCompletedEventHandler(object sender, OpisObavezanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OpisObavezanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OpisObavezanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PorukaOpisCompletedEventHandler(object sender, PorukaOpisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PorukaOpisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PorukaOpisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ZabraniBuduciDatumCompletedEventHandler(object sender, ZabraniBuduciDatumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZabraniBuduciDatumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZabraniBuduciDatumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PorukaDatumCompletedEventHandler(object sender, PorukaDatumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PorukaDatumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PorukaDatumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DajSezonskaPravilaCompletedEventHandler(object sender, DajSezonskaPravilaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DajSezonskaPravilaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DajSezonskaPravilaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SezonaDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SezonaDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void MinimalnaPovrsinaCompletedEventHandler(object sender, MinimalnaPovrsinaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MinimalnaPovrsinaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MinimalnaPovrsinaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DozvoliPreklapanjeCompletedEventHandler(object sender, DozvoliPreklapanjeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DozvoliPreklapanjeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DozvoliPreklapanjeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PorukaPreklapanjeCompletedEventHandler(object sender, PorukaPreklapanjeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PorukaPreklapanjeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PorukaPreklapanjeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FullAmountRequiresAllCompletedEventHandler(object sender, FullAmountRequiresAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FullAmountRequiresAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FullAmountRequiresAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ObavezneAktivnostiCompletedEventHandler(object sender, ObavezneAktivnostiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObavezneAktivnostiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObavezneAktivnostiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ObaveznaAktivnostDto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ObaveznaAktivnostDto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DelimicnoOdobrenjeDozvoljenoCompletedEventHandler(object sender, DelimicnoOdobrenjeDozvoljenoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DelimicnoOdobrenjeDozvoljenoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DelimicnoOdobrenjeDozvoljenoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DelimicnoOdobrenjeNacinCompletedEventHandler(object sender, DelimicnoOdobrenjeNacinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DelimicnoOdobrenjeNacinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DelimicnoOdobrenjeNacinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ProcenatPoAktivnostiCompletedEventHandler(object sender, ProcenatPoAktivnostiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcenatPoAktivnostiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcenatPoAktivnostiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void PorukaAkoNijePunoCompletedEventHandler(object sender, PorukaAkoNijePunoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PorukaAkoNijePunoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PorukaAkoNijePunoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591